// sigma-react/src/components/login.js
import React, { Component } from 'react'
import { InputText } from 'primereact/inputtext'
import { Button } from 'primereact/button'
import UserService from '../service/UserService'

export class login extends Component {
    constructor(props) {
        super(props)
        this.userService = new UserService();
    
        this.state = {
             username: "",
             password: "",
        }
        this.OnLogin = this.OnLogin.bind(this);
        this.handleChange = this.handleChange.bind(this);
    }
    
    handleChange(event) {
        this.setState({[event.target.name]: event.target.value});
    }

    OnLogin = async () =>{
        const user = this.state.username
        const pwd = this.state.password
        try{
            const res = await this.userService.Login({user,pwd})
            if(res.status === 200){
                alert("authorized")
                window.location = '/'
            }
        }
        catch(err){
            if(err.response.status === 400);
            alert("incorrect username or password")
        }
    }

    render() {
        return (
            <div>
                <div className="p-grid p-justify-center">
                    <div className="p-sm-12 p-md-6">
                        <div className="p-inputgroup">
                            <span className="p-inputgroup-addon"><i className="pi pi-user"></i></span>
                            <InputText value={this.state.username} name="username" onChange={this.handleChange} placeholder="username" style={{width:"100%"}}></InputText>
                        </div>
                    </div>
                </div>
                <div className="p-grid p-justify-center">
                    <div className="p-sm-12 p-md-6">
                        <div className="p-inputgroup"><span className="p-inputgroup-addon"><i className="pi pi-lock"></i></span>
                            <InputText value={this.state.password} name={"password"} onChange={this.handleChange} placeholder="password" type="password" style={{width:"100%"}}></InputText>
                        </div>
                    </div>
                </div>
                <div className="p-grid p-justify-center">
                    <div className="p-sm-12 p-md-6">
                        <Button to={`/usdf`} label="Login" style={{width:"100%"}} onClick={this.OnLogin} />
                    </div>
                </div>
            </div>
        )
    }
}

// sigma-vue/src/components/login.vue
<template>
  <div>
    <div class="p-grid p-fluid p-jc-center">
      <div class="p-col-12 p-md-4">
        <div class="p-inputgroup">
          <span class="p-inputgroup-addon">
            <i class="pi pi-user"></i>
          </span>
          <InputText placeholder="Username" v-model="username" />
        </div>
      </div>
    </div>
    <div class="p-grid p-fluid p-jc-center">
      <div class="p-col-12 p-md-4">
        <div class="p-inputgroup">
          <span class="p-inputgroup-addon">
            <i class="pi pi-lock"></i>
          </span>
          <Password v-model="password" placeholder="Password" />
        </div>
      </div>
    </div>
    <div class="p-grid p-fluid p-jc-center">
      <div class="p-col-6 p-md-2">
        <a href="/#/register">create account</a>
      </div>
      <div class="p-col- p-md-2" style="text-align: right">
        <a>forgot password</a>
      </div>
    </div>
    <div class="p-grid p-fluid p-jc-center">
      <div class="p-col-12 p-md-4">
        <Button label="Login" @click="login" />
      </div>
    </div>
  </div>
</template>

<script>
	import AuthService from '../service/AuthService'
	export default {
		data() {
			return {
				username: '',
				password: '',
			}
		},
		authService: null,
		created () {
			this.authService = new AuthService();
		},
		methods: {
			login() {
				console.log(this.username+'_'+this.password);
				this.authService.login({user:this.username,pwd:this.password}).then(data => console.log(data))
				// window.location='/#/'
			}
		},
	};
</script>

<style lang="scss" scoped>
</style>
