// sigma-vue-master/src/components/login.vue
<template>
    <div>
        <div class="p-grid p-jc-center">
            <div class="p-col-6">
                <div class="p-inputgroup">
                    <span class="p-inputgroup-addon">
                        <i class="pi pi-user"></i>
                    </span>
                    <InputText v-model="username" placeholder="username"></InputText>
                </div>
            </div>
        </div>
        <div class="p-grid p-jc-center">
            <div class="p-col-6">
                <div class="p-inputgroup">
                    <span class="p-inputgroup-addon">
                        <i class="pi pi-lock"></i>
                    </span>
                    <InputText type="password" v-model="password" placeholder="password"></InputText>
                </div>
            </div>
        </div>
        <div class="p-grid p-jc-center">
            <div class="p-col-6">
                <a href="/#/sigup">create account</a>
            </div>
        </div>
        <div class="p-grid p-jc-center">
            <div class="p-col-6">
                <Button label="Login" style="width:100%" @click="login"></Button>
            </div>
        </div>
        <alert v-model="dalert" :content="dcontent"/>
    </div>
</template>

<script>
import Axios from 'axios'
import alert from './alert.vue'
    export default {
        components: {
            alert,
        },
        data() {
            return {
                dalert: false,
                dcontent: '',
                username: '',
                password: '',
            }
        },
        methods: {
            async login() {
                const f_Username = this.username;
                const f_Password = this.password;
                try{
                    const res = await Axios.post("http://localhost:3000/api/auth",{f_Username,f_Password})
                    console.log(res);
                    localStorage.setItem('user',JSON.stringify(res.data.payload))
                    window.location = "/#/";
                }
                catch(err){
                    if(err.response.status == 400){
                        this.dalert = true
                        this.dcontent = 'sai tài khoản hoặc mật khẩu'
                    }
                }
            }
        },
    }
</script>

<style lang="scss" scoped>

</style>

// sigma-react/src/components/login.js
import React, { Component } from 'react'
import { InputText } from 'primereact/inputtext'
import { Button } from 'primereact/button'
import UserService from '../service/UserService'

export class login extends Component {
    constructor(props) {
        super(props)
        this.userService = new UserService();
    
        this.state = {
             username: "",
             password: "",
        }
        this.OnLogin = this.OnLogin.bind(this);
        this.handleChange = this.handleChange.bind(this);
    }
    
    handleChange(event) {
        this.setState({[event.target.name]: event.target.value});
    }

    OnLogin = async () =>{
        const user = this.state.username
        const pwd = this.state.password
        try{
            const res = await this.userService.Login({user,pwd})
            if(res.status === 200){
                alert("authorized")
                window.location = '/'
            }
        }
        catch(err){
            if(err.response.status === 400);
            alert("incorrect username or password")
        }
    }

    render() {
        return (
            <div>
                <div className="p-grid p-justify-center">
                    <div className="p-sm-12 p-md-6">
                        <div className="p-inputgroup">
                            <span className="p-inputgroup-addon"><i className="pi pi-user"></i></span>
                            <InputText value={this.state.username} name="username" onChange={this.handleChange} placeholder="username" style={{width:"100%"}}></InputText>
                        </div>
                    </div>
                </div>
                <div className="p-grid p-justify-center">
                    <div className="p-sm-12 p-md-6">
                        <div className="p-inputgroup"><span className="p-inputgroup-addon"><i className="pi pi-lock"></i></span>
                            <InputText value={this.state.password} name={"password"} onChange={this.handleChange} placeholder="password" type="password" style={{width:"100%"}}></InputText>
                        </div>
                    </div>
                </div>
                <div className="p-grid p-justify-center">
                    <div className="p-sm-12 p-md-6">
                        <Button to={`/usdf`} label="Login" style={{width:"100%"}} onClick={this.OnLogin} />
                    </div>
                </div>
            </div>
        )
    }
}
